### ISSUE TITLE
Backup problems with MinIO

### ISSUE THREAD

**Issue by mhkarimi1383** [cloudnative-pg/cloudnative-pg#3993]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

info@karimi.dev

### Version

1.22.1

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Other

### How did you install the operator?

Helm

### What happened?

Hi
I have successfully installed cloudnative-pg on my K8s cluster
But when I want to use the backup features with MinIO storage I will get into trouble that

First of all Access Key and Secret Key is not passed correctly (envs are not set) and fixed by manually setting env field in Cluster manifest (or given creds in secret in not working some how)

Also the -e option in barman cloud cli for wal archiving is not getting set I have set AES256 but barman is trying to use kms (@mikewallace1979 I think this one relates to barman)

### Cluster resource

```shell
## TODO
```

### Relevant log output

```shell
## TODO
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mhkarimi1383** [comment]
Update: Encryption problem solved by setting encryption to empty string :)
but problem for env vars are persist
